version: '3'
services:
  mongo-seed:
    container_name: "mongo-seed"
    build: ./mongo-seed
    links:
      - mongo-db
  mongo-db:
    image: mongo:3.6-jessie
    container_name: "mongo-db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - "27017:27017"
